[package]
name = "lisp-std-fs"
version = "0.1.0"
authors = ["Nathan Faucett <nathanfaucett@gmail.com>"]

keywords = ["lisp", "std", "fs"]
categories = []

description = "lisp std file system"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/nathanfaucett/rs-lisp.git"
homepage = "https://github.com/nathanfaucett/rs-lisp"

[lib]
name = "lisp_std_fs"
path = "src/lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
lisp = { git = "https://github.com/nathanfaucett/rs-lisp" }

[dev-dependencies]